package com.example.data

import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit

@JsonClass(generateAdapter = true)
data class GeminiContentPart(val text: String)

@JsonClass(generateAdapter = true)
data class GeminiContentRecord(val parts: List<GeminiContentPart>)

@JsonClass(generateAdapter = true)
data class GeminiRequest(val contents: List<GeminiContentRecord>)

@JsonClass(generateAdapter = true)
data class GeminiCandidate(val content: GeminiContentRecord)

@JsonClass(generateAdapter = true)
data class GeminiResponse(val candidates: List<GeminiCandidate>?)

interface GeminiApi {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}

object GeminiClient {
    private val moshi = Moshi.Builder()
        .add(KotlinJsonAdapterFactory())
        .build()

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    val apiService: GeminiApi by lazy {
        Retrofit.Builder()
            .baseUrl("https://generativelanguage.googleapis.com/")
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(GeminiApi::class.java)
    }

    suspend fun generateContent(apiKey: String, prompt: String): String {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return "Gemini API key is not configured in the Secrets panel. Set GEMINI_API_KEY to receive real AI financial insights."
        }
        val request = GeminiRequest(
            contents = listOf(
                GeminiContentRecord(
                    parts = listOf(
                        GeminiContentPart(prompt)
                    )
                )
            )
        )
        return try {
            val response = apiService.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "No response generated by the AI model."
        } catch (e: Exception) {
            "Failed to contact Gemini AI: ${e.localizedMessage}"
        }
    }
}
